### ISSUE TITLE
Obtaining predicted values and MSE, MAE for out_of_sample_size hold-out in auto_arima

### ISSUE THREAD

**Issue by SureshArr** [tgsmith61591/pmdarima#111]
#### Description
When using the parameter out_of_sample_size in auto_arima, how do you obtain the predictions made for those time points and the MSE or MAE value associated with it?

**Comment by tgsmith61591** [comment]
You can access the OOB score (either MSE or MAE) with `your_model.oob_`. The OOB preds will be available under `your_model.oob_preds_` starting in version 1.2.0.

**Comment by tgsmith61591** [comment]
Merged into `develop`, and will be released with 1.2.0 (slated for release in early May). If you need this feature ASAP, you can build from source on that branch!

**Comment by SureshArr** [comment]
Thanks for your prompt response!  It is great to have auto arima in python.
