### ISSUE TITLE
How to determine the best value for m?

### ISSUE THREAD

**Issue by vibhashahani** [tgsmith61591/pmdarima#119]
I have an hourly data looking like this:
Datetime                      Count
2014-04-26 09:00:00    154
2014-04-26 10:00:00    200
2014-04-26 11:00:00    200
2014-04-26 12:00:00    228
2014-04-26 13:00:00    206 

This is the seasonal decomposition
![download](https://user-images.githubusercontent.com/31318823/55469127-6e3ed880-5622-11e9-9a0c-cdb5dc807b0d.png)

#### Steps/Code to Reproduce

So, what should be the best way to determine m for data?

**Comment by tgsmith61591** [comment]
There's no perfect answer to this. I have a section on it in [the documentation](https://www.alkaline-ml.com/pmdarima/tips_and_tricks.html#setting-m). And Rob Hyndman did a nice [blog post](https://robjhyndman.com/hyndsight/seasonal-periods/) over it.

Short answer, you have to set it
