### ISSUE TITLE
How to get the insample prediction interval

### ISSUE THREAD

**Issue by PyDataBlog** [tgsmith61591/pmdarima#125]
After fitting a step wise model, how can I get the default (95% interval) for the insample prediction?

**Comment by tgsmith61591** [comment]
This is not *currently* implemented for in-sample predictions, but is for out-of-sample forecasts. I do think it would be really valuable, though. I'll add a research spike around this for the v1.2.0 release we're hoping to get out in early May.

**Comment by tgsmith61591** [comment]
I'm not quite sure I understand. If you're looking for a work-around to be able to implement this, you'll need to interact with the `statsmodels` internals and you'll basically end up implementing the feature itself.

The way we're handling it for out-of-sample is [this block of code](https://github.com/tgsmith61591/pmdarima/blob/master/pmdarima/arima/arima.py#L527). We'll have to do something similar to allow similar in-sample behavior.

Short answer, there's no direct work-around.
