### ISSUE TITLE
predict_in_sample of auto_arima produces fitted-values fluctuating around zero

### ISSUE THREAD

**Issue by JahangirVajedsamiei** [tgsmith61591/pmdarima#140]
#### Description
predict_in_sample of auto_arima produces fitted-values fluctuating around zero, does not follow real data pattern (see the blue line in actual results)! The expected result is made by sm.ARIMA using the same parameters as the auto-arima.

#### Steps/Code to Reproduce

model_auto = pm.auto_arima(array, start_p=0, start_q=0, max_p=10, max_q=10, max_d=3, error_action="ignore", seasonal=False, D=None, trace=True, stepwise=True, enforce_stationarity=False, enforce_invertibility=False, maxiter=5000)  
model_auto.summary()
model_auto.fit(array)
preds = model_auto.predict_in_sample(array)
plt.plot(preds, color='blue')

from statsmodels.tsa.arima_model import ARIMA
model = ARIMA(array, order=(1,1,2)).fit(disp=0)
predict = model.predict(typ='levels')
plt.plot(array, color='lightblue')
plt.plot(predict,color='green')

-->

#### Expected Results
![Screen Shot 2019-05-08 at 5 19 07 PM](https://user-images.githubusercontent.com/50415382/57386836-82dc3680-71b5-11e9-95f2-62d8bd9a50e0.png)

#### Actual Results
![Screen Shot 2019-05-08 at 5 15 20 PM](https://user-images.githubusercontent.com/50415382/57386860-925b7f80-71b5-11e9-933a-c1d3238d32d5.png)

**Comment by tgsmith61591** [comment]
My guess is #138 is going to address this. We weren't un-integrating the predictions back into the original endogenous space.

**Comment by JahangirVajedsamiei** [comment]
Thank you, for the fast reply! I look forward to the fix.
best,

**Comment by tgsmith61591** [comment]
@JahangirVajedsamiei could you provide a reproducible data example so I can start addressing this?

**Comment by JahangirVajedsamiei** [comment]
> @JahangirVajedsamiei could you provide a reproducible data example so I can start addressing this?

Here is an exemplary dataframe in excel. It is the respiration rate of a marine mussel over time.
Thank you in advance!
[array.xlsx](https://github.com/tgsmith61591/pmdarima/files/3170641/array.xlsx)

**Comment by fmv1992** [comment]
I'm also affected by the `.predict_in_sample` returns results around `1e-10` values.

**Comment by tgsmith61591** [comment]
See above. #138 should hopefully address this in the next release.

**Comment by suprememingjie** [comment]
@tgsmith61591 
Hi
Coould you tell me why my first in-sample prediction always starts with 0.

code below:
fitted, conf_int = arima_fit.predict_in_sample(return_conf_int=True, alpha=0.05)
fitted, conf_int = arima_fit.predict_in_sample(return_conf_int=True, alpha=0.05,dynamic=True)

I have tried both, results are same.

Many Thanks 
Oli

**Comment by tgsmith61591** [comment]
This was addressed a while ago. What version are you running?

**Comment by suprememingjie** [comment]
> This was addressed a while ago. What version are you running?

pmdarima version 1.8.2
python 3.6.8

**Comment by tgsmith61591** [comment]
Could you provide a minimally reproducible example including code and data?

**Comment by suprememingjie** [comment]
`
import numpy as np
import pandas as pd
from pmdarima import auto_arima
import pmdarima as pm
import matplotlib.pyplot as plt
[monthly-beer-production-in-austr.csv](https://github.com/alkaline-ml/pmdarima/files/7214673/monthly-beer-production-in-austr.csv)

df = pd.read_csv('monthly-beer-production-in-austr.csv')
df.Month = pd.to_datetime(df.Month)
df = df.set_index("Month")
input_df=df[:-12]
fc_df=df[-12:]

arima_fit=arima.fit(input_df.values)
arima=auto_arima(input_df, seasonal=True, m=12,max_p=7, max_d=5,max_q=7, max_P=4, max_D=4,max_Q=4)
fitted, conf_int = arima_fit.predict_in_sample(return_conf_int=True, alpha=0.05)
plt.plot(input_df)

plt.plot(hd_series,color='red')
plt.fill_between(hdlower_series.index,
                 hdlower_series,
                 hdupper_series,
                 color='k', alpha=.15)
plt.show()
`

**Comment by tgsmith61591** [comment]
@suprememingjie your final model results in an `ARIMA(order=(5, 1, 4), scoring_args={}, seasonal_order=(1, 0, 1, 12)`. Since there is a differencing term (d=1) it is impossible for us to predict a value for the first observation, since the model was fit over lag values. This produces some junky values for the first `d` indices when predicting in-sample. Rather than truncate and leave them out, they are returned as zeroes so the results match dimensionally with the ground truth. It may make more sense for us to return the first `d` samples as `np.nan` so it's clear what's happening... we'll think on that.

When I omit the first result, here's what I see:

```python
In [21]: fitted, conf_int = arima_fit.predict_in_sample(return_conf_int=True, alpha=0.05)
    ...: plt.plot(input_df)
    ...:
    ...: hd_series = pd.Series(fitted[1:], index=input_df.index[1:])
    ...: hdlower_series = pd.Series(conf_int[1:, 0], index=input_df.index[1:])
    ...: hdupper_series = pd.Series(conf_int[1:, 1], index=input_df.index[1:])
    ...:
    ...: plt.plot(hd_series,color='red')
    ...: plt.fill_between(hdlower_series.index,
    ...: hdlower_series,
    ...: hdupper_series,
    ...: color='k', alpha=.15)
    ...: plt.show()
```

![image](https://user-images.githubusercontent.com/6124706/134675029-8f2bf8b6-f2dc-4e06-af4b-38b0257a1494.png)

By the way, as a quick side note, the `auto_arima` function returns a fitted model, so this line in your code is unnecessary and can be removed:

```python
# no need to fit this again:
arima_fit = arima.fit(input_df.values)
```

**Comment by suprememingjie** [comment]
@tgsmith61591 aha, I made sense the day before yesterday before saw your comment, and also I did the same as you told omitting the first observation which produce the same plot.  Anyway, thanks for your kind help. Hope you , your team and your country are well.

Best wish
