### ISSUE TITLE
import pmdarima.arima causes value error

### ISSUE THREAD

**Issue by harshalzele** [tgsmith61591/pmdarima#143]
#### Description
import pmdarima.arima causes value error. I am using anaconda notebooks.

#### Steps/Code to Reproduce
import pmdarima.arima 

#### Expected Results
successfull package load

#### Actual Results
AttributeError: type object 'pmdarima.arima._arima.array' has no attribute '__reduce_cython__'

#### Versions
Windows-10-10.0.16299-SP0
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
NumPy 1.15.4
SciPy 1.2.1
Scikit-Learn 0.20.3
Pandas 0.24.2
Statsmodels 0.9.0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-06ca06df9c85> in <module>()
      6 import pandas; print("Pandas", pandas.__version__)
      7 import statsmodels; print("Statsmodels", statsmodels.__version__)
----> 8 import pmdarima; print("pmdarima", pmdarima.__version__)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pmdarima\__init__.py in <module>()
     27 
     28     # Stuff we want at top-level
---> 29     from .arima import auto_arima, ARIMA, AutoARIMA
     30     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf
     31 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pmdarima\arima\__init__.py in <module>()
      3 # Author: Taylor Smith <taylor.smith@alkaline-ml.com>
      4 
----> 5 from .approx import *
      6 from .arima import *
      7 from .auto import *

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pmdarima\arima\approx.py in <module>()
     17 # and since the platform might name the .so file something funky (like
     18 # _arima.cpython-35m-darwin.so), import this absolutely and not relatively.
---> 19 from pmdarima.arima._arima import C_Approx
     20 
     21 __all__ = [

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pmdarima\arima\_arima.cp37-win_amd64.pyd in init pmdarima.arima._arima()

AttributeError: type object 'pmdarima.arima._arima.array' has no attribute '__reduce_cython__'

**Comment by tgsmith61591** [comment]
Looks like a duplicate of #91. Can you try updating NumPy?

**Comment by harshalzele** [comment]
> Looks like a duplicate of #91. Can you try updating NumPy?

Thank you tgsmith61591 for quick help. It solved the problem.

Though i am not sure, but while upgrading numpy it updated mkl lib and seems it fixed the problem.
