### ISSUE TITLE
simple_differencing

### ISSUE THREAD

**Issue by jeweinberg** [tgsmith61591/pmdarima#146]
Can you expose the simple_differencing option or allow us to pass kwargs to the ARIMA and SARIMA class instantiation methods into the auto_arima class? This helps in some cases where fitting is prohibitively slow.

**Comment by tgsmith61591** [comment]
Care to take a crack at a PR?

**Comment by tgsmith61591** [comment]
Was hoping we'd get someone else to contribute this feature, but given the amount of time it's been open I merged it in #171. Will be available in 1.3.0 or immediately if building from `master`
