### ISSUE TITLE
How can one fit auto arima for daily data?

### ISSUE THREAD

**Issue by PyDataBlog** [tgsmith61591/pmdarima#149]
All the examples typically use non-daily data. How can one specify and fit auto-arima to daily data?

**Comment by aaronreidsmith** [comment]
I believe what you're talking about is covered [here](https://www.alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.auto_arima.html#pmdarima.arima.auto_arima) and [here](https://www.alkaline-ml.com/pmdarima/tips_and_tricks.html#period) in our docs. You should just need to set `m=7` for daily seasonality. Let us know if that answers your question

**Comment by tgsmith61591** [comment]
It also depends on the seasonal periodicity in your data, which we don't know. Take a look at [Rob Hyndman's blog post](https://robjhyndman.com/hyndsight/seasonal-periods/) on this topic.
