### ISSUE TITLE
RFC: Move away from gitflow

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pmdarima#150]
### Description

 We currently use the [gitflow](https://nvie.com/posts/a-successful-git-branching-model/) branching model, and some of our CI/CD practices and assumptions rely heavily on it. However, there are some drawbacks:

* Harder for new contributors to get the flow (pardon the pun) of our merging practices
* Lower visibility from issue-watchers into the resolution, as fixes never make it into master until a release happens

And more pros to moving off of it, IMO:

* Increased perception that we're responding to issues in a timely manner
* Easier for new contributors to submit PRs to the `master` branch than having to correct the PR every time
* In situations where pypi releases are broken (like due to the statsmodels/scipy bug when scipy upgraded to 1.13 and statsmodels was still behind), it's easier to instruct users to build from source on master than from some obscure `develop` branch
* Less likely to get merge conflicts in PRs because forks are probably not going to be based on the most bleeding edge branch

### Proposal

Prior to 1.3.0 I think we should move away from gitflow merging practices. Here are the changes required

* PRs will merge straight into `master`
* Releases will still be triggered by tagging
* We'll no longer manually version the package; we'll allow git tags to manage the versioning, and development versions will use a dummy version
* Bleeding edge (`develop`) documentation will now be published on `master` rather than `develop`
* Release documentation will now be published on releases rather than `master`
* Contributions instructions will have to change
* (`anything else?...`)

#### Thoughts please?

**Comment by aaronreidsmith** [comment]
Just got a chance to sit down and look at this.

I don't think our CI/CD needs to change that much. All of them currently rely on tagging for release. I believe some of them _do_ rely on a merge into master to run specific tests, but we could easily change that logic to be applied only on tags.

I think as far as your proposal, you hit everything. I can handle the CI/CD and contribution instructions. I can also look into the documentation (since a lot of that is contained in the CircleCI stuff anyway).

**Comment by charlesdrotar** [comment]
So I have seen both paradigms out in the "wild", and there is definitely a push away from using an explicit dev branch. I would argue in terms of simplicity of contribution it makes sense.

Also moving away from manual versioning makes a lot of sense. I can think of a few times where it crept up into a PR and someone had to keep a keen eye on that portion of the code. One less little thing to be confusing.

Also looking at the graphical branch history of commits won't potentially look like spaghetti as much... although I do like 🍝.
