### ISSUE TITLE
Changes to latest version

### ISSUE THREAD

**Issue by germayneng** [tgsmith61591/pmdarima#152]
Hello! ,

Was there any major changes to pmdarima? I  fitted a model previously in v 1.0.0. I installed the latest pmdarima and auto arima does not give the same output. Only by downgrading was i able to get the same output. 

Was there any major changes ?

```
stepwise_model = pmd.auto_arima(temp['Units'],start_p=0, start_q=0, start_P = 0, start_Q = 0,
                               m=12,
                               seasonal=True,trace=False,
                               error_action='ignore',
                               suppress_warnings=True,
                               stepwise=True)
```

example:

```
temp['Units'] = [119,189,160,141,130,196,108,139,130,156,178,193]
```

**Comment by tgsmith61591** [comment]
There were definitely major changes, most of which can always be [viewed here](https://www.alkaline-ml.com/pmdarima/whats_new.html). Whether the default for `trace` changed or not, I don't recall, but you have it set to `False` which is probably your issue.
