### ISSUE TITLE
issue with auto.arima import in Kaggle

### ISSUE THREAD

**Issue by storabian** [tgsmith61591/pmdarima#162]
Kaggle doesn't have **pyramid** library. So I need to install it using `!pip install pyramid-arima`
and `!pip install pyramid`.

But after that, when I want to import **auto_arima**:
```from pyramid.arima import auto_arima```

Kaggle show me an error:
> ImportError: cannot import name 'factorial'

**Comment by tgsmith61591** [comment]
The package name changed to `pmdarima` some time ago. See #34 for background.

Run:

```
pip install pmdarima
```

**Comment by storabian** [comment]
Uh, I see it now. I changed the name to `pmdarima` in my Kernel, but still the issue is exists when I call the it:

`from pmdarima import AutoARIMA, auto_arima`
> ImportError: cannot import name 'factorial'

**Comment by storabian** [comment]
> The package name changed to `pmdarima` some time ago. See #34 for background.
> 
> Run:
> 
> ```
> pip install pmdarima
> ```

Uh, I see it now. I changed the name to `pmdarima` in my Kernel, but still the issue is exists when I call the it:

`from pmdarima import AutoARIMA, auto_arima`
> ImportError: cannot import name 'factorial'

**Comment by tgsmith61591** [comment]
Part of the issue template asks for versions of various packages. Can you please post the version of scipy? Betting you need to bump it.

**Comment by storabian** [comment]
> Part of the issue template asks for versions of various packages. Can you please post the version of scipy? Betting you need to bump it. (Should be >= 1.3)
I've just checked in Kaggle, the current version is:
> scipy                     1.2.2

**Comment by storabian** [comment]
> > Part of the issue template asks for versions of various packages. Can you please post the version of scipy? Betting you need to bump it. (Should be >= 1.3)
> 
> I've just checked in Kaggle, the current version is:
> **scipy 1.2.2**

Now I've upgraded the scipy to the latest version and trying to see if the issue is fixed with it

**Comment by tgsmith61591** [comment]
Upgrade your scipy (and probably statsmodels while you're at it) :-) you can try:

```
pip install --ignore-installed scipy statsmodels
```

**Comment by storabian** [comment]
> > > Part of the issue template asks for versions of various packages. Can you please post the version of scipy? Betting you need to bump it. (Should be >= 1.3)
> > 
> > 
> > I've just checked in Kaggle, the current version is:
> > **scipy 1.2.2**
> 
> Now I've upgraded the scipy to the latest version and trying to see if the issue is fixed with it

Okay, I have used below lines to upgrade Scipy library and statsmodels:
```
!pip install --upgrade scipy
!pip install --ignore-installed scipy statsmodels
```

Then installed pmdarima library:
`!pip install pmdarima`

But find a new error when I call **auto_arima**:
`ImportError: cannot import name 'lstsq'`

**Comment by aaronreidsmith** [comment]
That is probably your `numpy` version. `pmdarima` requires `numpy>=1.15`.

**Comment by storabian** [comment]
> That is probably your `numpy` version. `pmdarima` requires `numpy>=1.15`.

Actually not, the `numpy` version is up-to-date in my Kernel

**Comment by tgsmith61591** [comment]
Sadegh, these are all problems with other packages. Can you *please* post the versions of the packages as requested in the template?

Numpy
Scipy
Scikit-learn
Statsmodels

**Comment by storabian** [comment]
> Sadegh, these are all problems with other packages. Can you _please_ post the versions of the packages as requested in the template?
> 
> Numpy
> Scipy
> Scikit-learn
> Statsmodels

For sure, here are the versions:
**numpy                     1.16.4
scipy                     1.2.2
scikit-learn              0.21.2
statsmodels               0.9.0**

**Comment by tgsmith61591** [comment]
Your scipy and statsmodels are still not updated.

**Comment by storabian** [comment]
> Your scipy and statsmodels are still not updated.

You're right, it seems **Kaggle** has issues upgrading the libraries inside its Kernels. I'll try to fix it and get back to you again.

**Comment by tgsmith61591** [comment]
We can't solve Kaggle's kernel issues. I think the solution has been made fairly clear at this point, so I'm going to lock this conversation. If there are other problems (not Kaggle's internal problems), feel free to open another issue.
