### ISSUE TITLE
exception on importing pmdarima1.2.1 on win10

### ISSUE THREAD

**Issue by mprosperi** [tgsmith61591/pmdarima#165]
**Describe the bug**
I'm on a virtualenv on win 10 and after installing and importing I get the following exception

(af437) C:\Users\user1>pip install pmdarima
Collecting pmdarima
  Downloading https://files.pythonhosted.org/packages/a3/1b/7687cca9931d78ff359e1bd7485791be583f9ab343b50cf23863e0269d30/pmdarima-1.2.1-cp37-cp37m-win_amd64.whl (304kB)
    100% |████████████████████████████████| 307kB 3.3MB/s
Requirement already satisfied: six>=1.5 in c:\users\user1\envs\af437\lib\site-packages (from pmdarima) (1.11.0)
Requirement already satisfied: Cython>=0.29 in c:\users\user1\envs\af437\lib\site-packages (from pmdarima) (0.29.2)
Requirement already satisfied: scipy<1.3,>=1.2 in c:\users\user1\envs\af437\lib\site-packages (from pmdarima) (1.2.1)
Requirement already satisfied: numpy>=1.15 in c:\users\user1\envs\af437\lib\site-packages (from pmdarima) (1.15.3+mkl)
Requirement already satisfied: joblib>=0.11 in c:\users\user1\envs\af437\lib\site-packages (from pmdarima) (0.13.2)
Requirement already satisfied: scikit-learn>=0.19 in c:\users\user1\envs\af437\lib\site-packages (from pmdarima) (0.20.0)
Requirement already satisfied: pandas>=0.19 in c:\users\user1\envs\af437\lib\site-packages (from pmdarima) (0.24.2)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\user1\envs\af437\lib\site-packages (from pmdarima) (0.10.0)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\user1\envs\af437\lib\site-packages (from pandas>=0.19->pmdarima) (2.7.3)
Requirement already satisfied: pytz>=2011k in c:\users\user1\envs\af437\lib\site-packages (from pandas>=0.19->pmdarima) (2018.5)
Requirement already satisfied: patsy>=0.4.0 in c:\users\user1\envs\af437\lib\site-packages (from statsmodels>=0.9.0->pmdarima) (0.5.1)
Installing collected packages: pmdarima
Successfully installed pmdarima-1.2.1
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(af437) C:\Users\user1>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pmdarima.arima import auto_arima
C:\Users\user1\Envs\af437\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user1\Envs\af437\lib\site-packages\pmdarima\__init__.py", line 29, in <module>
    from .arima import auto_arima, ARIMA, AutoARIMA
  File "C:\Users\user1\Envs\af437\lib\site-packages\pmdarima\arima\__init__.py", line 5, in <module>
    from .approx import *
  File "C:\Users\user1\Envs\af437\lib\site-packages\pmdarima\arima\approx.py", line 19, in <module>
    from pmdarima.arima._arima import C_Approx
  File "__init__.pxd", line 918, in init pmdarima.arima._arima
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by aaronreidsmith** [comment]
Others have solved this by upgrading [`numpy` to `1.16`](https://github.com/scikit-learn-contrib/hdbscan/issues/272#issuecomment-453958532). Try a `pip install --upgrade numpy` and see if that works. We may need to change our minimum version of `numpy`

**Comment by mprosperi** [comment]
upgraded numpy to 1.16.4 and it works
