### ISSUE TITLE
difference in custom function

### ISSUE THREAD

**Issue by sattar-hazrati** [tgsmith61591/pmdarima#172]
I want to change difference function to my custom formula . 
if series x1, x2, x3,... difference calculate by r1 = (x2 - x1) / x1 , r2 = (x3 - x2) / x2 , .... .
for example : 
                x = c ( 10, 4, 2, 9, 34)
                 = (4 - 10 )/10 , (2 -  4 )/4, (9 - 2 )/9, (34 - 9)/34
                 = -0.6, -0.5, 0.77 ,  0.73

My question is how to change diff function to my own formula?

**Comment by tgsmith61591** [comment]
There's not going to be a straightforward way to do this... Differencing is ubiquitous enough that we didn't make it extensible...
