### ISSUE TITLE
unable to coda install pmdarima

### ISSUE THREAD

**Issue by pksw2016** [tgsmith61591/pmdarima#173]
**Describe the bug**

**To Reproduce**  
typed the following in terminal - 
conda install -c saravji pmdarima

```python
(Pk) prasads-imac:Pk prasadkamath$ conda install -c saravji pmdarima
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: 
```

**Versions**

Darwin-18.6.0-x86_64-i386-64bit
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:30:03) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Traceback (most recent call last):
  File "/Users/prasadkamath/.conda/envs/Pk/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-df0eca425da7>", line 3, in <module>
    import pmdarima; print("pmdarima", pmdarima.__version__)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: No module named 'pmdarima'

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by tgsmith61591** [comment]
Conda dists aren't available yet. They will be with the release of 1.3.0, shortly. In the meantime run `pip install pmdarima`
