### ISSUE TITLE
Weird residual values when differencing (d) > 0

### ISSUE THREAD

**Issue by notdsr** [tgsmith61591/pmdarima#175]
After running auto.arima model, when I am trying to get the residual values the value it gives for the 1st data point when differencing parameter (d) >0 is wrong. I have attached the screenshot for the reference. Since in my case d is equal to 1 so in the plot we can see that predicted values are 1 period of lag. My current model is SARIMAX(1, 1, 1)x(1, 0, 0, 52). Post-processing is req
<img width="396" alt="bug1" src="https://user-images.githubusercontent.com/13780176/62516047-9abd6800-b841-11e9-82d4-286dd0714846.PNG">
<img width="602" alt="bug2" src="https://user-images.githubusercontent.com/13780176/62516048-9abd6800-b841-11e9-99dd-130412ff3f7b.PNG">

uired to get the right values.

**Comment by tgsmith61591** [comment]
Unfortunately that's going to be a known side effect of differencing, since the entire algorithm is fit over `n - d` samples.

Best advice I can give is start your residual plot from `d`.

**Comment by notdsr** [comment]
Got it! But that's not the case in R, there is some post-processing is being done to get the right values.

**Comment by tgsmith61591** [comment]
As close as we try to be to R's forecast package, it's not 1:1. You could probably back into that value, but it may be a pain. If you end up figuring it out, PRs are always welcome!

**Comment by tgsmith61591** [comment]
Closing this. But welcome a PR if you figure out a way to back into it...
