### ISSUE TITLE
How can I get the best order and seasonal_order when AutoArima completes

### ISSUE THREAD

**Issue by jackwang2** [tgsmith61591/pmdarima#177]
**Question**
I can set the parameter trace to True, and it print the model list for ARIMA fit. But is there any explicit method that I can use to tell me what's the best order and seasonal_order that fill the model?

**Versions (if necessary)**

Darwin-18.2.0-x86_64-i386-64bit
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
pmdarima 1.2.1
NumPy 1.16.2
SciPy 1.2.1
Scikit-Learn 0.20.3
Statsmodels 0.9.0

**Comment by tgsmith61591** [comment]
It returns a fitted ARIMA model. If the model is named `model`, just call `model.order` or `model.seasonal_order`.

Pro-tip, in python you can call the `dir` function on an object to get it's attributes.

**Comment by jackwang2** [comment]
> It returns a fitted ARIMA model. Just call `model.order` or `model.seasonal_order`, where `model` is the returned ARIMA.
> 
> Pro-tip, in python you can call the `dir` function on an object to get it's attributes.

Thanks @tgsmith61591, I got the parameter values by `model.model_`
