### ISSUE TITLE
Any inverse function for pmdarima.utils.diff?

### ISSUE THREAD

**Issue by jackwang2** [tgsmith61591/pmdarima#180]
I am just curious that is there any inverse function like `diffinv`  in `R` for pmdarima.utils.diff?

**Comment by jackwang2** [comment]
I got this resolved by implementing the some logic of `diffinv` in R:

`
#  create a differenced series
def difference(dataset, lag=1):
    diff = list()
    for i in range(lag, len(dataset)):
        value = dataset[i] - dataset[i - lag]
        diff.append(value)
    return np.array(diff)

# the inverse function of the lagged differences function difference
def inverse_difference(x, xi, lag):    
    n = len(x) if type(x) == list else x.shape[0]

    y = np.zeros(n + lag)
    y[:lag] = xi[:lag]

    for i in range(lag, n + lag):
        y[i] = x[i - lag] + y[i - lag]

    return y[lag : n + lag]
`

The test cod and result is as below:
`
xs = [1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

diff = difference(np.array(xs), lag=5)
inverse_difference(diff, xi=[1,3,5,7,9], lag=5)
`

array([ 2.,  4.,  6.,  8., 10.])

**Comment by tgsmith61591** [comment]
Would you be interested in making a PR?

**Comment by jackwang2** [comment]
@tgsmith61591 Sure, I will make a PR later.

**Comment by aaronreidsmith** [comment]
@tgsmith61591 Tagging you so our new [Stale bot](https://github.com/probot/stale) doesn't close this
