### ISSUE TITLE
regularizing autoArima model

### ISSUE THREAD

**Issue by fissehab** [tgsmith61591/pmdarima#185]
I am fitting regression with ARIMA errors using auto.arima. Since I suspect, the models could be over-fit, I want to use regularization with it. Is it possible to implement lasso or elastic net regularization ?

**Comment by tgsmith61591** [comment]
Unfortunately this is not possible. We use stats models under the hood and to the best of my efforts to read into this, they don't allow it. I found an [interesting answer](https://stats.stackexchange.com/questions/152202/regularization-for-arima-models) on stack exchange about this, but it's not something we'll support in the foreseeable future.
