### ISSUE TITLE
automatic InvBoxCox for predictions

### ISSUE THREAD

**Issue by ihadanny** [tgsmith61591/pmdarima#197]
not entirely sure this is possible with your pipeline approach...

R's `forecast.arima` has a `lambda` parameter which calls an internal `Transformer` when it's not NONE. This enables it to automatically `InvBoxCox` the  predictions and the confidence intervals, which is very useful to users. (can't think of why would I want the transformed results, the original scale is the intuitive scale...)

NOTE that the metrics (log-likelihood, aic, bic...) are reported in the transformed scale, so this part is ok.

**Comment by tgsmith61591** [comment]
Merged in #198
