### ISSUE TITLE
tsCV support

### ISSUE THREAD

**Issue by ihadanny** [tgsmith61591/pmdarima#201]
can you please supply a port of `tsCV`?
It's a very simple function, and for me it's the only reliable way of evaluating my out-of-sample model performance. I don't know if it belongs in `pmdarima` or in `statsmodels`, but it's definitely *not* the sklearn `TimeSeriesSplit`, `tsCV` is much better. 

Here's what I sketched for my internal needs, I'm pretty sure you have a more complete version you use for your own testing and evaluations:

```
def tsCV(y, model, h=1, step=1, window=None, xreg=None):
    n = len(y)
    if xreg:
        assert (len(xreg) == n)
    if not window:
        indx = range(1, n, step)
        e = np.zeros([(n - 1) // step, h])
    else:
        indx = range(window, n, step)
        e = np.zeros([(n - window) // step, h])
    start_params = None
    for out_i, i in enumerate(indx):
        start = 0 if not window else i - window
        assert i >= 0
        y_subset = y[start: i]

        if xreg:
            xreg_subset = xreg[start: i]
        else:
            xreg_subset = None
        if start_params:
            model.fit(y_subset, exogenous=xreg_subset, arima__start_params=start_params)
        else:
            model.fit(y_subset, exogenous=xreg_subset)
        preds = model.predict(n_periods=h)
        e[out_i, :] = y[i:i + h] - preds

    return e
```

**Comment by tgsmith61591** [comment]
The only currently supported CV approach is the out-of-sample CV used when fitting the model. I do agree it's a long-overdue feature, and one for which I've kicked ideas around before. I think there are probably some more robust ways we can get CV into the package that won't be a 1:1 port of the `tsCV` function, but will support the same general functionality.

I can come up with the base classes and functionality, and then feel more than welcome to submit a PR for any added bells and whistles you'd like :)

**Comment by tgsmith61591** [comment]
Fixed in #203. Here's [an example of how to use it](https://www.alkaline-ml.com/pmdarima/develop/auto_examples/model_selection/example_cross_validation.html#sphx-glr-auto-examples-model-selection-example-cross-validation-py)

**Comment by ihadanny** [comment]
cool! what do you mean by `when not performing using a window`?

**Comment by tgsmith61591** [comment]
Guess you're talking about `The size of step taken to increase the training sample size when not performing using a window.`. That's a doc artifact from before I split the CV class into two separate ones. For the sliding window CV, should just read: `The size of step taken between training folds`. 🙂 If you wanna correct that and submit a PR, feel free, otherwise I can fix it in the next PR I submit.
