### ISSUE TITLE
pmdarima fails frequently with "initial MA coefficients are not invertible" where R succeeds

### ISSUE THREAD

**Issue by ihadanny** [tgsmith61591/pmdarima#202]
I'm fitting a very simple model for the `taylor` series from R's forecast library, and trying to reproduce it with `pmdarima`:

If I do this:
`Arima(taylor, order=c(0,0,1), lambda = NULL)` 
and this:
`arima.ARIMA(order=(0,0,1), trace=1, seasonal=False, transparams=True, with_intercept=True).fit(taylor)`
I get the **exact** same model. And the same works if I use order `(0,0,1)`.

However, if I try order `(1,0,1)` R fits it nicely, while `pmdarima` fails with: `ValueError: The computed initial MA coefficients are not invertible`. 

Why is that? Is there something not implemented in the `pmdarima` impl? or am I missing something in the way I execute it?

It's also frequently failing with `initial AR coefficients are not stationary` where R does not (can open a separate bug for reproducing this if needed)

**Comment by tgsmith61591** [comment]
I'll look into it. Keep in mind the ARIMA implementation itself uses statsmodels under the hood. Perhaps you could start sleuthing there. I've got several issues to dig through in my (limited) spare time, so any investigation you can do on your own always makes the maintainer's life easier.

**Comment by ihadanny** [comment]
ok, I made some progress, but still confused.

apparently this has to do with an old issue that deals with differences in approach between R `stats` package and python `statsmodels` package: [https://github.com/statsmodels/statsmodels/issues/1155/](url) , also [https://github.com/statsmodels/statsmodels/issues/5629](url) and others.

ARIMA models require stationarity of AR terms, and invertibility of MA terms. This can be tested by making sure the inverse roots (1/r) of the AR and MA lag operator polynoms are all within the unit circle. 

The R implementation somehow knows to enforce these constraints on its fitted model, but it can be borderline (almost outside the unit circle). In my case:
```
> 1/forecast:::arroots(fit2)$roots
[1] 0.9813966+0i
> 1/forecast:::maroots(fit2)$roots
[1] -0.7123106+0i
```

and you can see that the AR term is almost not-stationary (which means that the model's predictions won't be good). I gathered that in such cases the method `statsmodels` uses to estimate the starting parameters fails instead of generating this unstable model. 

But that still doesn't explain why in this model the AR term is the problematic one, while the error message talks about the MA term...

**Comment by tgsmith61591** [comment]
Awesome sleuthing! Thanks for taking a look into this. Chad Fulton had a suggestion on one of the threads:

> In particular, you can pass your own starting parameters, for example setting the "bad' values to zeros.

In fact, the SARIMAX model in statsmodels seems like it will do this automatically. However, `pmdarima` only uses a SARIMAX if the seasonal order is non-None. I can force a SARIMAX to fit in this fashion by zeroing out the seasonal order:

```python
>>> model = arima.ARIMA(order=(1,0,1), seasonal_order=(0, 0, 0, 0), transparams=True, with_intercept=True).fit(taylor)
/anaconda3/envs/pmdenv/lib/python3.6/site-packages/statsmodels/tsa/statespace/sarimax.py:949: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/anaconda3/envs/pmdenv/lib/python3.6/site-packages/statsmodels/tsa/statespace/sarimax.py:961: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/anaconda3/envs/pmdenv/lib/python3.6/site-packages/statsmodels/base/model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)
>>> model
ARIMA(callback=None, disp=0, maxiter=None, method=None, order=(1, 0, 1),
   out_of_sample_size=0, scoring='mse', scoring_args=None,
   seasonal_order=(0, 0, 0, 0), solver='lbfgs', start_params=None,
   suppress_warnings=False, transparams=True, trend=None,
   with_intercept=True)
>>> model.predict(5)
array([22454.91502187, 22460.22253038, 22465.5125742 , 22470.78521078,
       22476.04049741])
```

And when I inspect the inverted roots, I get virtually the same results as in R:

```python
>>> 1/model.arroots()
array([0.99670944])
>>> 1/model.maroots()
array([-0.7028633])
```

**Comment by ihadanny** [comment]
also, how can you force a SARIMAX on auto_arima?

**Comment by ihadanny** [comment]
wow great! got perfect match between the 2 libraries when I use the `seasonal_order=(0, 0, 0, 0)` trick, and also make sure to sync the `with_intercept=False` with the `include.drift=FALSE` which is the default for `forecast:::Arima`. 

thanks so much, go ahead and close - just one last question: should there any indication for the model being `borderline` and `junky` in the confints or the s.e for the arima terms? or is the only way to detect that this happened is by checking the roots of the polynoms?

**Comment by tgsmith61591** [comment]
I suppose you could try to force it like this:

```python
>>> arima.auto_arima(taylor, seasonal=True, transparams=True, with_intercept=False, start_P=0, D=0, start_Q=0, m=0, max_P=0, max_Q=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/taylor.smith/Documents/Personal/pmdarima/pmdarima/arima/auto.py", line 238, in auto_arima
    raise ValueError('m must be a positive integer (> 0)')
ValueError: m must be a positive integer (> 0)
```

but there's a check I have for values of `m`... I could back out the check for positive `m` if `D` is set (since no test of seasonality will occur), but I kinda think it's better not to. Now that we know a model can be forced with the `pmdarima.ARIMA` class directly, it feels dangerous to allow a backdoor into the `pmdarima.auto_arima`, since someone could accidentally get a bad model as a result of their grid search. I like the idea of `consenting adults are allowed to directly create their own bad model`, but I want to avoid it coming back in the `auto_arima` results.

As far as whether to warn for borderline unstable models, I think statsmodels does a really good job of blowing up the stack if you even get close to a bad set of parameters. The amount of effort you have to go through to force one of those models and the plethora of `HessianInversionWarnings` might be enough 😁
