### ISSUE TITLE
LogEndogTransformer

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pmdarima#205]
We currently have a [`BoxCoxEndogTransformer`](https://github.com/tgsmith61591/pmdarima/blob/master/pmdarima/preprocessing/endog/boxcox.py#L14). It would be nice to have a `LogEndogTransformer` as well.

**Comment by christopher-siewert** [comment]
Hi, I'd like to take this on.

As the log transform is a special case of the Box-Cox power transformation with a lambda of 0, would you like `LogEndogTransformer` to just be a wrapper that provides a default lambda of 0? 

Is this just for easy of use? Perhaps the fact that Box-Cox can be used for log (and others like square root) transforms should just be added to the docstring?

**Comment by tgsmith61591** [comment]
Cool, thanks for taking it!

I think you're right, the most elegant solution that reuses the most code possible would be for the log transformer to extend the boxcox transformer with `lmbda=0`. Might want to enforce that `y + lmbda2` is all positive and either raise or truncate with a warning if not. That's where re-using the existing boxcox code will be helpful, with `neg_action`.

RE: `is this for ease of use`, one reason I like the idea of a separate transformer (even if it reuses the same code by extension) is for the sake of explicitness. Something the R package does that's convenient, yet simultaneously a pain and difficult to reason about, is forcing way too many code paths into one function, and we've made a decision to opt for more classes in hopes that it improves interpretability and ease of use. That's why we'd be more in favor of an explicit class for log, one for sqrt, etc. Kinda like how scikit does it. Does that answer your question?

**Comment by christopher-siewert** [comment]
Absolutely, I'll get to work.

**Comment by christopher-siewert** [comment]
Hi, I've been looking at it some more. I'm new at this so I appreciate your patience.

Extending the boxcox transformer class is the easiest solution code wise. However, I think the documentation will be messed up. The `LogEndogTransformer` class will automatically inherit the `fit` and `fit_transform` methods, which don't really make sense in this case and will be very confusing in the sphinx generated docs. I don't think it's possible to not inherit a method, and I don't know anything about sphinx but going in and messing with the templates to not include all methods on just this class seems messy.

I looked at scikit learn's preprocessing package and they don't implement explicit classes for log or square root transforms. Instead they use a [custom function transformer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html) which is used for stateless transformations. Would it be best to implement something like this instead?

**Comment by tgsmith61591** [comment]
Hey thanks for looking at this, and no rush at all.

### RE: Doc

You are correct that subclasses will inherit documentation from superclasses. Don't worry about messing with Sphinx; it is a nightmare to edit templates! You can override documentation from a subclass:

```python
class A:
    """Super class

    Parameters
    ----------
    foo : int
        Description of foo
    (etc.)
    """
    def __init__(self, foo, bar, baz):
        self.foo = foo
        self.bar = bar
        self.baz = baz

    def do_foo(self):
        """Foo ^ 2 + (bar * baz)"""
        return self.foo ** 2 + (self.bar * self.baz)


# Extends A:
class B(A):
    """Subclass of A that doesn't use ``bar`` or ``baz``

    Parameters
    ----------
    foo : int
        Subclass description of foo
    """
    def __init__(self, foo):
        super().__init__(foo, 0, 0)

    def do_foo(self):
        """Squares foo and divides by two"""
        return super(B, self).do_foo() / 2
```

You can see that doc is appropriately overridden like so:

```
>>> print(B(5).__doc__)
Subclass of A that doesn't use ``bar`` or ``baz``

    Parameters
    ----------
    foo : int
        Subclass description of foo
```

So overriding doc isn't a major concern, because even if your method just needs to call the super method but with new doc, you can make it basically a pass-through to the super method, like `B.do_foo`. (I made sure to include an example where the subclass only uses a subset of hyperparams from the super class, like in the log transformer case. Notice it passes 0's in their place).

### RE: Transformers

I agree that it would be convenient to have a function transformer, where a user could pass anything in. I also think for sure that the sqrt transformation you're talking about fits into that use case. The explicit log transformation seems nice to me, since A) 90% of the code (including the error handling and validation) is written and B) there is a clearly-defined use case in time series analysis for log transformations.

To put it bluntly, if I were a user who found the BoxCox transformation, I would be surprised _not_ to find a log transformation as well. Does that make sense?

**Comment by christopher-siewert** [comment]
Thanks for all your advice. It's good to hear the thoughts of more experienced people

**Comment by tgsmith61591** [comment]
Thanks for your contribution! We love getting others involved. Feel free to take any other issues as they arise, if they pique your interest.
