### ISSUE TITLE
stationarity and invertibility checks in auto-arima

### ISSUE THREAD

**Issue by ihadanny** [tgsmith61591/pmdarima#208]
does pmdarima auto-arima check for invertibility and stationarity of the selected model? does it also check for almost-non-invertibility and almost-non-stationarity like in the R implementation?

**Comment by ihadanny** [comment]
just to clarify - by almost-non-invertibility I'm referring to this code: 
[https://github.com/robjhyndman/forecast/blob/master/R/newarima2.R](url)
```
    if (minroot < 1 + 1e-2) { # Previously 1+1e-3
      fit$ic <- Inf
} # Don't like this model
```

**Comment by tgsmith61591** [comment]
We don't currently have the `polyroot` test implemented, which is what this would require
