### ISSUE TITLE
always use SARIMAX instead of ARIMA, it is deprecated

### ISSUE THREAD

**Issue by ihadanny** [tgsmith61591/pmdarima#211]
see: https://github.com/statsmodels/statsmodels/issues/6225#issuecomment-550350284

**Comment by tgsmith61591** [comment]
Cool! This would actually make our lives significantly easier than having to straddle three different classes under the hood. Thanks for pointing this out to us!

**Comment by tgsmith61591** [comment]
Merged in #219
