### ISSUE TITLE
Vector ARIMA support

### ISSUE THREAD

**Issue by silviuzil** [tgsmith61591/pmdarima#215]
**Question**
Is there support for vector ARIMA models (VAR) in pmdarima? Couldn't find any reference (positive or negative) in the documentation. Thanks! 

**Versions (if necessary)**

**Comment by tgsmith61591** [comment]
Not currently, but cool idea! Looks like statsmodels supports it, so it's definitely something we could support in the future.

**Comment by silviuzil** [comment]
Thanks, I'll put it as a feature request. Maybe I'll implement it myself.

**Comment by tgsmith61591** [comment]
Feature request in #216
