### ISSUE TITLE
meaningful exog_names for the fourier terms variables generated by FourierFeaturizer

### ISSUE THREAD

**Issue by ihadanny** [tgsmith61591/pmdarima#222]
when asking for a `summary()` the fourier terms generated by `FourierFeaturizer` should have meaningful names like in R with their period and their order, (e.g. `S24-5` and `C24-5`) and not `x14` like now. 

this shouldn't be so hard, as for my own exogenous variables I'm already doing it, after the fit with `model.arima_res_.model.exog_names[1:1+len(ex_cols)] = ex_cols`

**Comment by tgsmith61591** [comment]
I think this is fair and should be pretty easy to handle

**Comment by ihadanny** [comment]
oops, for SARIMAX the above method doesn't work, you should do `model.arima_res_.data._param_names[:len(ex_cols)] = ex_cols` instead...

**Comment by ihadanny** [comment]
come to think of it - what about meaningful names also for my custom exogenous variables? do you think I should open another ticket for it? as in adding a `exog_names` parameters to the fit interface - the `x1` variables are really confusing

**Comment by tgsmith61591** [comment]
@ihadanny take a look at #226
