### ISSUE TITLE
AttributeError: module 'pyramid' has no attribute '__version__'

### ISSUE THREAD

**Issue by nikhilsharma010** [tgsmith61591/pmdarima#34]
#### Description
I was trying to read about ARIMA models via this link

https://medium.com/@josemarcialportilla/using-python-and-auto-arima-to-forecast-seasonal-time-series-90877adff03c

and while training the model i got the following error
#### Expected Results

The resulting best model parameters should give us an AIC value of 1771.29.

#### Actual Results

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-8d09c2f9b8c9> in <module>()
      5                            error_action='ignore',
      6                            suppress_warnings=True,
----> 7                            stepwise=True)

/anaconda3/lib/python3.6/site-packages/pyramid/arima/auto.py in auto_arima(y, exogenous, start_p, d, start_q, max_p, max_d, max_q, start_P, D, start_Q, max_P, max_D, max_Q, max_order, m, seasonal, stationary, information_criterion, alpha, test, seasonal_test, stepwise, n_jobs, start_params, trend, method, transparams, solver, maxiter, disp, callback, offset_test_args, seasonal_test_args, suppress_warnings, error_action, trace, random, random_state, n_fits, return_valid_fits, out_of_sample_size, scoring, scoring_args, **fit_args)
    626 
    627         # fit a baseline p, d, q model and then a null model
--> 628         stepwise_wrapper.fit_increment_k_cache_set(True)  # p, d, q, P, D, Q
    629         stepwise_wrapper.fit_increment_k_cache_set(
    630             True, p=0, q=0, P=0, Q=0)  # null model

/anaconda3/lib/python3.6/site-packages/pyramid/arima/auto.py in fit_increment_k_cache_set(self, expr, p, q, P, Q)
    779                              out_of_sample_size=self.out_of_sample_size,
    780                              scoring=self.scoring,
--> 781                              scoring_args=self.scoring_args)
    782 
    783             # use the orders as a key to be hashed for

/anaconda3/lib/python3.6/site-packages/pyramid/arima/auto.py in _fit_arima(x, xreg, order, seasonal_order, start_params, trend, method, transparams, solver, maxiter, disp, callback, fit_params, suppress_warnings, trace, error_action, out_of_sample_size, scoring, scoring_args)
    846                     out_of_sample_size=out_of_sample_size, scoring=scoring,
    847                     scoring_args=scoring_args)\
--> 848             .fit(x, exogenous=xreg, **fit_params)
    849 
    850     # for non-stationarity errors or singular matrices, return None

/anaconda3/lib/python3.6/site-packages/pyramid/arima/arima.py in fit(self, y, exogenous, **fit_args)
    375         # As of version 0.7.2, start saving the version with the model so
    376         # we can track changes over time.
--> 377         self.pkg_version_ = pyramid.__version__
    378         return self
    379 

AttributeError: module 'pyramid' has no attribute '__version__'

#### Versions
 1 import pyramid; print("Pyramid", pyramid.__version__)

AttributeError: module 'pyramid' has no attribute '__version__'

-->

**Comment by tgsmith61591** [comment]
Hey thanks for the issue. Can you run `conda list` in your environment?

**Comment by nikhilsharma010** [comment]
# packages in environment at /anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0  
alabaster                 0.7.10           py36h174008c_0  
anaconda-client           1.6.14                   py36_0  
anaconda-navigator        1.8.7                    py36_0  
anaconda-project          0.8.2            py36h9ee5d53_0  
appnope                   0.1.0            py36hf537a9a_0  
appscript                 1.0.1            py36h9e71e49_1  
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.3                    py36_0  
astropy                   3.0.2            py36h917ab60_1  
attrs                     18.1.0                   py36_0  
babel                     2.5.3                    py36_0  
backcall                  0.1.0                    py36_0  
backports                 1.0              py36ha3c1827_1  
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2  
beautifulsoup4            4.6.0            py36h72d3c9f_1  
bitarray                  0.8.1            py36h1de35cc_1  
bkcharts                  0.2              py36h073222e_0  
blas                      1.0                         mkl  
blaze                     0.11.3           py36h02e7a37_0  
bleach                    2.1.3                    py36_0  
blosc                     1.14.3               hd9629dc_0  
bokeh                     0.12.16                  py36_0  
boto                      2.48.0           py36hdbc59ac_1  
bottleneck                1.2.1            py36hbd380ad_0  
box.py                    1.2.8                     <pip>
boxsdk                    1.5.5                     <pip>
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
cachetools                2.1.0                     <pip>
certifi                   2018.4.16                py36_0  
cffi                      1.11.5           py36h342bebf_0  
chardet                   3.0.4            py36h96c241c_1  
click                     6.7              py36hec950be_0  
cloudpickle               0.5.3                    py36_0  
clyent                    1.2.2            py36hae3ad88_0  
colorama                  0.3.9            py36hd29a30c_0  
colorlover                0.2.1                     <pip>
conda                     4.5.8                    py36_0  
conda-build               3.10.5                   py36_0  
conda-env                 2.6.0                h36134e3_0  
conda-verify              2.0.0            py36he837df3_0  
contextlib2               0.5.5            py36hd66e5e7_0  
cryptography              2.2.2            py36h1de35cc_0  
cufflinks                 0.14.4                    <pip>
curl                      7.60.0               ha441bb4_0  
cycler                    0.10.0           py36hfc81398_0  
cymem                     1.31.2           py36hfc679d8_0    conda-forge
cython                    0.28.2           py36h1de35cc_0  
cytoolz                   0.9.0.1          py36h1de35cc_0  
cytoolz                   0.8.2                     <pip>
dask                      0.17.5                   py36_0  
dask-core                 0.17.5                   py36_0  
datashape                 0.5.4            py36hfb22df8_0  
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py36_0  
dill                      0.2.8.2                   <pip>
dill                      0.2.8.2                  py36_0  
distributed               1.21.8                   py36_0  
docutils                  0.14             py36hbfde631_0  
dxfwrite                  1.2.1                     <pip>
en-core-web-sm            2.0.0                     <pip>
entrypoints               0.2.3            py36hd81d71f_2  
et_xmlfile                1.0.1            py36h1315bdc_0  
expat                     2.2.5                hb8e80ba_0  
fastcache                 1.0.2            py36h1de35cc_2  
filelock                  3.0.4                    py36_0  
flask                     1.0.2                    py36_1  
flask-cors                3.0.4                    py36_0  
freetype                  2.8                  h12048fb_1  
future                    0.16.0                    <pip>
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.3.0            py36h1de35cc_0  
glib                      2.56.1               h35bc53a_0  
glob2                     0.6              py36h94c9186_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py36hf9c35bd_2  
google-api-python-client  1.7.3                     <pip>
google-auth               1.5.0                     <pip>
google-auth-httplib2      0.0.3                     <pip>
greenlet                  0.4.13           py36h1de35cc_0  
h2o                       3.20.0.5                  <pip>
h5py                      2.7.1            py36ha8ecd60_2  
hdf5                      1.10.2               hfa1e0ec_1  
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1            py36h2f9c1c0_0  
httplib2                  0.11.3                    <pip>
hupper                    1.3                       <pip>
hypothesis                2.0.0                     <pip>
icu                       58.2                 h4b95b61_1  
idna                      2.6              py36h8628d0a_1  
imageio                   2.3.0                    py36_0  
imagesize                 1.0.0                    py36_0  
imutils                   0.4.6                     <pip>
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py36_0  
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36h241746c_0  
ipywidgets                7.2.1                    py36_0  
isort                     4.3.4                    py36_0  
itsdangerous              0.24             py36h49fbb8d_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py36_0  
jedi                      0.12.0                   py36_1  
jinja2                    2.10             py36hd36f9c5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py36hb385e00_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36hccf5b1c_1  
jupyter_core              4.4.0            py36h79cf704_0  
jupyterlab                0.32.1                   py36_0  
jupyterlab_launcher       0.10.5                   py36_0  
kiwisolver                1.0.1            py36h792292d_0  
lazy-object-proxy         1.3.1            py36h2fbbe47_0  
libcurl                   7.60.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                hcb84e12_1  
libxml2                   2.9.8                hab757c2_1  
libxslt                   1.1.32               hb819dd2_0  
llvmlite                  0.23.1           py36hc454e04_0  
locket                    0.2.0            py36hca03003_1  
lxml                      4.2.1            py36h7166777_0  
lzo                       2.10                 h362108e_2  
markupsafe                1.0              py36h3a1e703_1  
matplotlib                2.2.2            py36ha7267d0_0  
mccabe                    0.6.1            py36hdaeb55d_0  
mistune                   0.8.3            py36h1de35cc_1  
mkl                       2018.0.3                      1  
mkl-service               1.1.2            py36h7ea6df4_4  
mkl_fft                   1.0.1            py36h917ab60_0  
mkl_random                1.0.1            py36h78cc56f_0  
more-itertools            4.1.0                    py36_0  
mpc                       1.0.3                h7a72875_5  
mpfr                      3.1.5                h711e7fd_2  
mpmath                    1.0.0            py36hf1b8295_2  
msgpack                   0.5.6                     <pip>
msgpack-numpy             0.4.1                     <pip>
msgpack-numpy             0.4.3                    py36_0  
msgpack-python            0.5.4                     <pip>
msgpack-python            0.5.6            py36h04f5b5a_0  
multipledispatch          0.5.0                    py36_0  
murmurhash                0.28.0           py36h0a44026_0  
navigator-updater         0.2.1                    py36_0  
nbconvert                 5.3.1            py36h810822e_0  
nbformat                  4.4.0            py36h827af21_0  
ncurses                   6.1                  h0a44026_0  
networkx                  2.1                      py36_0  
nltk                      3.3.0                    py36_0  
nose                      1.3.7            py36h73fae2b_2  
notebook                  5.5.0                    py36_0  
nsepy                     0.7                       <pip>
numba                     0.38.0           py36h1702cab_0  
numexpr                   2.6.5            py36h057f876_0  
numpy                     1.14.3           py36h9bb19eb_1  
numpy-base                1.14.3           py36h479e554_1  
numpydoc                  0.8.0                    py36_0  
odo                       0.5.1            py36hc1af34a_0  
olefile                   0.45.1                   py36_0  
opencv-python             3.4.1.15                  <pip>
openpyxl                  2.5.3                    py36_0  
openssl                   1.0.2o               h26aff7b_0  
packaging                 17.1                     py36_0  
pandas                    0.23.0           py36h1702cab_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py36h3b0b094_1  
parso                     0.2.0                    py36_0  
partd                     0.3.8            py36hf5c4cb8_0  
PasteDeploy               1.5.2                     <pip>
path.py                   11.0.1                   py36_0  
pathlib                   1.0.1                     <pip>
pathlib2                  2.3.2                    py36_0  
patsy                     0.5.0                    py36_0  
pcre                      8.42                 h378b8a2_0  
pep8                      1.7.1                    py36_0  
pexpect                   4.5.0                    py36_0  
pickleshare               0.7.4            py36hf512f8e_0  
pillow                    5.1.0            py36hfcce615_0  
pip                       10.0.1                    <pip>
pip                       10.0.1                   py36_0  
pkginfo                   1.4.2                    py36_1  
plac                      0.9.6                      py_1    conda-forge
plac                      0.9.6                     <pip>
plaster                   1.0                       <pip>
plaster-pastedeploy       0.6                       <pip>
plotly                    3.2.1                     <pip>
pluggy                    0.6.0            py36hb1d0581_0  
ply                       3.11                     py36_0  
preshed                   1.0.0            py36h0a44026_0  
prompt_toolkit            1.0.15           py36haeda067_0  
psutil                    5.4.5            py36h1de35cc_0  
psycopg2                  2.7.5                     <pip>
psycopg2-binary           2.7.5                     <pip>
ptyprocess                0.5.2            py36he6521c3_0  
py                        1.5.3                    py36_0  
pyasn1                    0.4.3                     <pip>
pyasn1-modules            0.2.1                     <pip>
PyAutoGUI                 0.9.36                    <pip>
pycodestyle               2.4.0                    py36_0  
pycosat                   0.6.3            py36hee92d8f_0  
pycparser                 2.18             py36h724b2fc_1  
pycrypto                  2.6.1            py36h1de35cc_8  
pycurl                    7.43.0.1         py36hdbc3d79_0  
pyflakes                  1.6.0            py36hea45e83_0  
pygments                  2.2.0            py36h240cd3f_0  
pyimagesearch             0.4                       <pip>
pylint                    1.8.4                    py36_0  
PyMsgBox                  1.0.6                     <pip>
pyobjc                    4.2.2                     <pip>
pyobjc-core               4.2.2                     <pip>
pyobjc-framework-Accounts 4.2.2                     <pip>
pyobjc-framework-AddressBook 4.2.2                     <pip>
pyobjc-framework-AppleScriptKit 4.2.2                     <pip>
pyobjc-framework-AppleScriptObjC 4.2.2                     <pip>
pyobjc-framework-ApplicationServices 4.2.2                     <pip>
pyobjc-framework-Automator 4.2.2                     <pip>
pyobjc-framework-AVFoundation 4.2.2                     <pip>
pyobjc-framework-AVKit    4.2.2                     <pip>
pyobjc-framework-BusinessChat 4.2.2                     <pip>
pyobjc-framework-CalendarStore 4.2.2                     <pip>
pyobjc-framework-CFNetwork 4.2.2                     <pip>
pyobjc-framework-CloudKit 4.2.2                     <pip>
pyobjc-framework-Cocoa    4.2.2                     <pip>
pyobjc-framework-Collaboration 4.2.2                     <pip>
pyobjc-framework-ColorSync 4.2.2                     <pip>
pyobjc-framework-Contacts 4.2.2                     <pip>
pyobjc-framework-ContactsUI 4.2.2                     <pip>
pyobjc-framework-CoreBluetooth 4.2.2                     <pip>
pyobjc-framework-CoreData 4.2.2                     <pip>
pyobjc-framework-CoreLocation 4.2.2                     <pip>
pyobjc-framework-CoreML   4.2.2                     <pip>
pyobjc-framework-CoreServices 4.2.2                     <pip>
pyobjc-framework-CoreSpotlight 4.2.2                     <pip>
pyobjc-framework-CoreText 4.2.2                     <pip>
pyobjc-framework-CoreWLAN 4.2.2                     <pip>
pyobjc-framework-CryptoTokenKit 4.2.2                     <pip>
pyobjc-framework-DictionaryServices 4.2.2                     <pip>
pyobjc-framework-DiskArbitration 4.2.2                     <pip>
pyobjc-framework-EventKit 4.2.2                     <pip>
pyobjc-framework-ExceptionHandling 4.2.2                     <pip>
pyobjc-framework-ExternalAccessory 4.2.2                     <pip>
pyobjc-framework-FinderSync 4.2.2                     <pip>
pyobjc-framework-FSEvents 4.2.2                     <pip>
pyobjc-framework-GameCenter 4.2.2                     <pip>
pyobjc-framework-GameController 4.2.2                     <pip>
pyobjc-framework-GameKit  4.2.2                     <pip>
pyobjc-framework-GameplayKit 4.2.2                     <pip>
pyobjc-framework-ImageCaptureCore 4.2.2                     <pip>
pyobjc-framework-IMServicePlugIn 4.2.2                     <pip>
pyobjc-framework-InputMethodKit 4.2.2                     <pip>
pyobjc-framework-InstallerPlugins 4.2.2                     <pip>
pyobjc-framework-InstantMessage 4.2.2                     <pip>
pyobjc-framework-Intents  4.2.2                     <pip>
pyobjc-framework-IOSurface 4.2.2                     <pip>
pyobjc-framework-iTunesLibrary 4.2.2                     <pip>
pyobjc-framework-LatentSemanticMapping 4.2.2                     <pip>
pyobjc-framework-LaunchServices 4.2.2                     <pip>
pyobjc-framework-libdispatch 4.2.2                     <pip>
pyobjc-framework-LocalAuthentication 4.2.2                     <pip>
pyobjc-framework-MapKit   4.2.2                     <pip>
pyobjc-framework-MediaAccessibility 4.2.2                     <pip>
pyobjc-framework-MediaLibrary 4.2.2                     <pip>
pyobjc-framework-MediaPlayer 4.2.2                     <pip>
pyobjc-framework-ModelIO  4.2.2                     <pip>
pyobjc-framework-MultipeerConnectivity 4.2.2                     <pip>
pyobjc-framework-NetFS    4.2.2                     <pip>
pyobjc-framework-NetworkExtension 4.2.2                     <pip>
pyobjc-framework-NotificationCenter 4.2.2                     <pip>
pyobjc-framework-OpenDirectory 4.2.2                     <pip>
pyobjc-framework-Photos   4.2.2                     <pip>
pyobjc-framework-PhotosUI 4.2.2                     <pip>
pyobjc-framework-PreferencePanes 4.2.2                     <pip>
pyobjc-framework-PubSub   4.2.2                     <pip>
pyobjc-framework-QTKit    4.2.2                     <pip>
pyobjc-framework-Quartz   4.2.2                     <pip>
pyobjc-framework-SafariServices 4.2.2                     <pip>
pyobjc-framework-SceneKit 4.2.2                     <pip>
pyobjc-framework-ScreenSaver 4.2.2                     <pip>
pyobjc-framework-ScriptingBridge 4.2.2                     <pip>
pyobjc-framework-SearchKit 4.2.2                     <pip>
pyobjc-framework-Security 4.2.2                     <pip>
pyobjc-framework-SecurityFoundation 4.2.2                     <pip>
pyobjc-framework-SecurityInterface 4.2.2                     <pip>
pyobjc-framework-ServiceManagement 4.2.2                     <pip>
pyobjc-framework-Social   4.2.2                     <pip>
pyobjc-framework-SpriteKit 4.2.2                     <pip>
pyobjc-framework-StoreKit 4.2.2                     <pip>
pyobjc-framework-SyncServices 4.2.2                     <pip>
pyobjc-framework-SystemConfiguration 4.2.2                     <pip>
pyobjc-framework-Vision   4.2.2                     <pip>
pyobjc-framework-WebKit   4.2.2                     <pip>
pyodbc                    4.0.23           py36h0a44026_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0            py36hb281f35_0  
pyqt                      5.9.2            py36h11d3b92_0  
pyramid                   1.9.2                     <pip>
pyramid-arima             0.8.1                     <pip>
PyScreeze                 0.1.14                    <pip>
pysocks                   1.6.8                    py36_0  
pytables                  3.4.3            py36h5ca999c_2  
pytest                    3.5.1                    py36_0  
pytest-arraydiff          0.2                      py36_0  
pytest-astropy            0.3.0                    py36_0  
pytest-doctestplus        0.1.3                    py36_0  
pytest-openfiles          0.3.0                    py36_0  
pytest-remotedata         0.2.1                    py36_0  
python                    3.6.5                hc167b69_1  
python-box                3.2.0                     <pip>
python-dateutil           2.7.3                    py36_0  
python.app                2                        py36_8  
PyTweening                1.0.3                     <pip>
pytz                      2018.4                   py36_0  
pywavelets                0.5.2            py36h2710a04_0  
pyyaml                    3.12             py36h2ba1e63_1  
pyzmq                     17.0.0           py36h1de35cc_1  
qt                        5.9.5                h02808f3_0  
qtawesome                 0.4.4            py36h468c6fb_0  
qtconsole                 4.3.1            py36hd96c0ff_0  
qtpy                      1.4.1                    py36_0  
readline                  7.0                  hc1231fa_4  
regex                     2017.4.5                  <pip>
regex                     2018.06.21       py36h1de35cc_0  
repoze.lru                0.7                       <pip>
requests                  2.18.4           py36h4516966_1  
requests-toolbelt         0.8.0                     <pip>
retrying                  1.3.3                     <pip>
rope                      0.10.7           py36h68959ac_0  
rsa                       3.4.2                     <pip>
ruamel_yaml               0.15.35          py36h1de35cc_1  
scikit-image              0.13.1           py36h1de35cc_1  
scikit-learn              0.19.1           py36hffbff8c_0  
scipy                     1.1.0            py36hcaad992_0  
seaborn                   0.8.1            py36h595ecd9_0  
semver                    2.8.1                      py_1    conda-forge
send2trash                1.5.0                    py36_0  
setuptools                39.1.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3          py36hf20db9d_0  
sip                       4.19.8           py36h0a44026_0  
six                       1.11.0           py36h0e22d5e_1  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1            py36h6c7b616_0  
sortedcollections         0.6.1                    py36_0  
sortedcontainers          1.5.10                   py36_0  
spacy                     2.0.11           py36h6440ff4_2  
sphinx                    1.7.4                    py36_0  
sphinxcontrib             1.0              py36h9364dc8_1  
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1  
sputnik                   0.9.3                    py36_0    conda-forge
spyder                    3.2.8                    py36_0  
sqlalchemy                1.2.7            py36hb402a30_0  
sqlite                    3.23.1               hf1716c9_0  
statsmodels               0.9.0            py36h917ab60_0  
sympy                     1.1.1            py36h7f3cf04_0  
tabulate                  0.8.2                     <pip>
tblib                     1.3.2            py36hda67792_0  
termcolor                 1.1.0                    py36_1  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h625a49b_0  
thinc                     6.11.2           py36hf9f1f73_1  
thinc                     6.10.2                    <pip>
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                    py36_0  
tornado                   5.0.2                    py36_0  
tqdm                      4.23.4                   py36_0  
traitlets                 4.3.2            py36h65bd3ce_0  
translationstring         1.3                       <pip>
typing                    3.6.4                    py36_0  
ujson                     1.35             py36h470a237_1    conda-forge
unicodecsv                0.14.1           py36he531d66_0  
unixodbc                  2.3.6                h3efe00b_0  
uritemplate               3.0.0                     <pip>
urllib3                   1.22             py36h68b9469_0  
venusian                  1.1.0                     <pip>
Wand                      0.4.4                     <pip>
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1            py36h3b9701d_1  
WebOb                     1.8.2                     <pip>
werkzeug                  0.14.1                   py36_0  
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.2.1                    py36_0  
wrapt                     1.10.11          py36hc29e774_0  
xlrd                      1.1.0            py36h336f4a2_1  
xlsxwriter                1.0.4                    py36_0  
xlwings                   0.11.8                   py36_0  
xlwt                      1.2.0            py36h5ad1178_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h378b8a2_0  
zict                      0.1.3            py36h71da714_0  
zlib                      1.2.11               hf3cbc9b_2  
zope.deprecation          4.3.0                     <pip>
zope.interface            4.5.0                     <pip>

**Comment by tgsmith61591** [comment]
Seems my worst fear on this project has come to fruition 😃 There is a near-name collision with another package on pypi (pyramid). When you `import pyramid`, it takes the first one alphabetically in your environment, and the Pyramid framework is different from the ARIMA package. I was hoping to avoid this, but it means the name of the package itself will eventually need to change... here's how I'll probably address this:

* Maintain status quo through release 0.9.X with deprecation warnings
* Beginning in version 0.10.X, we'll need to change the name of the package several thoughts here...
  * Migrate git repo to new namespace (not ideal)
  * Change the package name (a la scikit-learn/sklearn) that one would import, and also all associated documentation. This is probably the preferred approach.

Pinging @charlesdrotar for your thoughts

**Comment by nikhilsharma010** [comment]
Oh... That i didn't expected. 

What should be immediate fix ?

**Comment by tgsmith61591** [comment]
Immediate fix would be to create a new conda environment and install pyramid-arima (but not the other pyramid package)

**Comment by charlesdrotar** [comment]
@tgsmith61591 The way I see it is how much convenience in terms of automation and behavior would change for the end users.

 I think maybe the easiest and best approach like you were saying is to just change the package name for importing the package (`import pyramid` becomes `import pyramid-arima` possibly). That would mean that any automation for installing the package would stay the same, but the importing would still obviously need to change to avoid this error and with DeprecationWarnings this may help address any potential confusion that may occur. I would also suggest a similar/identical warning within the *README* and even an update in all future release sphinx docs using an appropriate warning format (included within sphinx) for those who are not updating the package as frequently and wouldn’t have that patch included in their version to note the change pre/post 0.10.0.

Migrating the repo seems less ideal like you were saying :). Hope this helps!

**Comment by bertjwregeer** [comment]
As a core developer for Pyramid, the web framework, `pyramid-*` packages tend to be extensions to be used with `pyramid`. I would have been really surprised if I had stumbled on `pyramid-arima` and it was not a `pyramid` extension.

**Comment by tgsmith61591** [comment]
Yep. The plan is to eventually migrate to `pmdarima` and away from the current `pyramid-arima`. The original name came from a near anagram of "py" + "arima", but it's no longer punny given the namespace troubles 😄

**Comment by tgsmith61591** [comment]
This has been solved by #46. Here are the release notes:

v1.0.0
------

* **Wheels will no longer be built for Python versions < 3.5.** You may still be able to build
  from source, but support for 2.x python versions will diminish in future versions.

* Migrate namespace from 'pyramid-arima' to 'pmdarima'. This is due to the fact that
  a growing web-framework (also named Pyramid) is causing namespace collisions when
  both packages are installed on a machine. See [Issue #34](https://github.com/tgsmith61591/pmdarima/issues/34)
  for more detail.

* Remove redundant Travis tests

* Automate documentation build on Circle CI

* Move lots of the build/test functionality into the `Makefile` for ease.

* Warn for impending deprecation of various environment variable name changes. The following
  will be completely switched over in version 1.2.0:

  - `'PYRAMID_MPL_DEBUG'` will become `'PMDARIMA_MPL_DEBUG'`
  - `'PYRAMID_MPL_BACKEND'` will become `'PMDARIMA_MPL_BACKEND'`
  - `'PYRAMID_ARIMA_CACHE_WARN_SIZE'` will become `'PMDARIMA_CACHE_WARN_SIZE'`

**Comment by divyajyotisingh01** [comment]
SyntaxError: positional argument follows keyword argument
why this error is shown

**Comment by tgsmith61591** [comment]
@divyajyotisingh01 as I told you in a separate thread, please __[open a new issue](http://www.alkaline-ml.com/pmdarima/contributing.html#filing-bugs)__ (click that green "New Issue" button at the top right of this page) and share your code, the *entire* error, and what you were trying to do.

This issue has *nothing* to do with your error.
