### ISSUE TITLE
No Intercept

### ISSUE THREAD

**Issue by Jacyle** [tgsmith61591/pmdarima#50]
#### Description
Would like to be able to run the models without an intercept by having a 'no intercept' option. I looked through the documentation and did not see a way to do this. Thanks.

**Comment by tgsmith61591** [comment]
`statsmodels` technically support this under the hood with the `trend` fit parameter (setting to 'nc') but it currently breaks `auto_arima` in some scenarios. I have to look into whether this is a `SARIMAX` vs. `ARMA` vs. `ARIMA` issue or if it's actually on the `pmdarima` side, but I agree this would be useful to document and test.

**Comment by tgsmith61591** [comment]
Finished this feature up in 1fa57e8. This will be released in v1.1.0
