### ISSUE TITLE
Create plotting tests that test output as well as execution

### ISSUE THREAD

**Issue by charlesdrotar** [tgsmith61591/pmdarima#59]
#### Description

It looks like we are testing that the plot is generated and not the actual contents of the plot for [pmdarima.arima.tests.test_arima.test_plot_diagnostics()](https://github.com/tgsmith61591/pmdarima/blob/develop/pmdarima/arima/tests/test_arima.py#L765-L778). Matplotlib has a way of addressing this. See example [here](https://matplotlib.org/devel/testing.html#writing-an-image-comparison-test). What we have is a good start, but we should implement the test in a way that will help catch potential plotting snafus that may randomly come up by underlying changes to matplotlib.

#### Steps/Code to Reproduce

```bash
python -m pytest pmdarima
```
#### Expected Results

It is expected that the execution of the test will test against a know image file.

#### Actual Results

At this moment there is no test against the output.

#### Versions

Current version using branch of pmdarima develop: `1.1.0-dev0`

**Comment by tgsmith61591** [comment]
Done in #60
