### ISSUE TITLE
Clean up Travis CI scripts

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pmdarima#82]
#### Description

Many of the Travis scripts are a bit outdated. There are several environment variables we no longer set in the `.travis.yml` so script some logic is redundant or unused.

This is a minor issue that's really just tech-debt related.

**Comment by charlesdrotar** [comment]
Another low-hanging fruit CI tech debt opportunity that can be clubbed into this effort, is the use of `assert_raises` instead of `with pytest.raises(<INSERT ERROR HERE>):`. We can remove the custom code and let pytest handle this.

**Comment by charlesdrotar** [comment]
Resolved by [pull#83](https://github.com/tgsmith61591/pmdarima/pull/83).
