### ISSUE TITLE
Trouble with install pmdarima with python 3.7

### ISSUE THREAD

**Issue by crowszr** [tgsmith61591/pmdarima#85]
Hi, I have some issues with install pmdarima by using pip install. At first, it said I need install vs tool 14.0, I follow the instructions but there still have some error for install pmdarima.

Here is the error message I copy from cmd.

Building wheels for collected packages: pyramid-arima
  Running setup.py bdist_wheel for pyramid-arima ... error
  Complete output from command C:\Users\crows\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\crows\\AppData\\Local\\Temp\\pip-install-pfuhaavw\\pyramid-arima\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\crows\AppData\Local\Temp\pip-wheel-7o440zly --python-tag cp37:
  Partial import of pyramid during the build process.
  Requirements: ['Cython>=0.23\nnumpy>=1.10\nscipy>=0.9\nscikit-learn>=0.17\npandas>=0.19\nstatsmodels>=0.9.0\n']
  Adding extra setuptools args
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:/Users/crows/Anaconda3\\Library\\lib']
    NOT AVAILABLE

 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\crows\Anaconda3\lib\site-packages\numpy\core\include -Ipyramid\arima\_arima_fast_helpers.h -IC:\Users\crows\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\crows\Anaconda3\include -IC:\Users\crows\Anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcpyramid\arima\_arima.c /Fobuild\temp.win-amd64-3.7\Release\pyramid\arima\_arima.obj
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\crows\Anaconda3\lib\site-packages\numpy\core\include -Ipyramid\arima\_arima_fast_helpers.h -IC:\Users\crows\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\crows\Anaconda3\include -IC:\Users\crows\Anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcpyramid\arima\_arima.c /Fobuild\temp.win-amd64-3.7\Release\pyramid\arima\_arima.obj" failed with exit status 2

**Comment by crowszr** [comment]
I use pip install pyramid_arima

**Comment by crowszr** [comment]
I resolve this problem by install old version python&Anaconda(python 3.6x anaconda3-5.2.0)

**Comment by tgsmith61591** [comment]
You're installing the old package. Try:

```bash
$ pip install pmdarima
```
