### ISSUE TITLE
Not working with Python 3.7

### ISSUE THREAD

**Issue by HumbleLearner** [tgsmith61591/pmdarima#87]
I am trying to install the package i python 3.7 using pip.

using command:- pip install pyramid-arima

it is throwing below error ;-

Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\humble_learner\\AppData\\Local\\Temp\\pip-install-vbnrc_ym\\pyrami
d-arima\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().rep
lace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --re
cord C:\Users\humble_learner\AppData\Local\Temp\pip-record-2ccw7qzc\install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in C:\Us
ers\humble_learner\AppData\Local\Temp\pip-install-vbnrc_ym\pyramid-arima\

**import platform; print(platform.platform())**
-Windows-7-6.1.7601-SP1
**import sys; print("Python", sys.version)**
-Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
**import pmdarima; print("pmdarima", pmdarima.__version__)**
-ModuleNotFoundError: No module named 'pmdarima'
**import numpy; print("NumPy", numpy.__version__)**
NumPy 1.15.4
**import scipy; print("SciPy", scipy.__version__)**
SciPy 1.1.0
**import sklearn; print("Scikit-Learn", sklearn.__version__)**
sklearn 0.19.2
**import statsmodels; print("Statsmodels", statsmodels.__version__)**
statsmodels 0.9.0

**Comment by charlesdrotar** [comment]
Hi @HumbleLearner.

 Please try to `pip install pmdarima` we have since migrated from the `pyramid-arima` namespace so as to not introduce a namespace collision of an already existing python library called `pyramid`.

**Comment by charlesdrotar** [comment]
See also [here](https://github.com/tgsmith61591/pmdarima/issues/85) for reference.

**Comment by HumbleLearner** [comment]
Thanks @charlesdrotar for quick reply. it works !
