### ISSUE TITLE
Appveyor caching may not be working as expected

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pmdarima#98]
#### Description

#97 reduced the amount Appveyor tests that are running, but I'm not sure the caching is working is expected... would be helpful if someone could dig into this

**Comment by aaronreidsmith** [comment]
I'm no AppVeyor expert, but in 58ac7db5ce0c53c4f61fe817d62245513bd50f51, you commented out two cache directories. Could it have anything to do with that? Or is this issue to investigate those?

**Comment by tgsmith61591** [comment]
Those don't seem to be doing the trick either :-) Want to find a way to cache pip-installed packages between builds. This may or may not be possible given our separate builds are slightly different architectures.

No rush on this... I tried it out and wanted to get some other ideas here.

**Comment by aaronreidsmith** [comment]
Fixed in #100. Closing
